name: CI

on:
  push:
    branches:
      - decaf

  pull_request:
    branches:
      - decaf

env:
  ruby_version: 3.3

jobs:
  smithy-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true

      - name: Test
        run: bundle exec rake smithy:spec

  smithy-client-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true

      - name: Test
        run: bundle exec rake smithy-client:spec

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rake rubocop
