name: Seahorse CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7, '3.0', 'jruby-9.3']

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v2

      - name: Install gems
        run: bundle install
        working-directory: ./seahorse

      - name: Unit tests
        run: bundle exec rspec
        working-directory: ./seahorse

  steep:
    runs-on: ubuntu-18.04

    steps:
      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0

      - uses: actions/checkout@v2

      - name: Bundle install
        run: |
          gem install bundler
          bundle install
        working-directory: ./seahorse

      - name: Type checks
        run: bundle exec steep check
        working-directory: ./seahorse

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0

      - uses: actions/checkout@v2

      - name: Bundle install
        run: |
          gem install bundler
          bundle install
        working-directory: ./seahorse

      - name: Rubocop
        run: bundle exec rubocop -E -S
        working-directory: ./seahorse
